export const SEED_ITEMS = [
  // Hair
  {
    itemId: 'hair_short',
    name: 'Short Adventurer Hair',
    type: 'hair',
    rarity: 'common',
    characterCompatibility: 'both',
    price: 0,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/hair/hair_short.svg',
    description: 'Practical, neat, and ready for swift action.',
  },
  {
    itemId: 'hair_spiky',
    name: 'Spiky Champion Locks',
    type: 'hair',
    rarity: 'uncommon',
    characterCompatibility: 'both',
    price: 150,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/hair/hair_spiky.svg',
    description: 'Anime-inspired wild hair that defies gravity.',
  },
  {
    itemId: 'hair_long',
    name: 'Sorceress Flowing Locks',
    type: 'hair',
    rarity: 'common',
    characterCompatibility: 'both',
    price: 0,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/hair/hair_long.svg',
    description: 'Long flowing hair woven with natural grace.',
  },
  {
    itemId: 'hair_braids',
    name: 'Valkyrie Battle Braids',
    type: 'hair',
    rarity: 'rare',
    characterCompatibility: 'both',
    price: 300,
    unlockRequirement: { type: 'level', value: 3 },
    asset: '/assets/items/hair/hair_braids.svg',
    description: 'Intricately braided locks worn by northern champions.',
  },

  // Head
  {
    itemId: 'bandana_red',
    name: "Rogue's Crimson Bandana",
    type: 'head',
    rarity: 'uncommon',
    characterCompatibility: 'both',
    price: 120,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/head/bandana_red.svg',
    description: 'A striking red bandana favored by stealthy scouts.',
  },
  {
    itemId: 'knight_helm',
    name: 'Crusader Greathelm',
    type: 'head',
    rarity: 'epic',
    characterCompatibility: 'both',
    price: 650,
    unlockRequirement: { type: 'level', value: 5 },
    asset: '/assets/items/head/knight_helm.svg',
    description: 'A solid steel helmet with gold trim for fearless knights.',
  },
  {
    itemId: 'golden_crown',
    name: 'Crown of Persistence',
    type: 'head',
    rarity: 'legendary',
    characterCompatibility: 'both',
    price: 1500,
    unlockRequirement: { type: 'streak', value: 7 },
    asset: '/assets/items/head/golden_crown.svg',
    description: 'Forged from radiant gold for masters of unbroken streaks.',
  },

  // Clothes
  {
    itemId: 'tunic_novice',
    name: 'Novice Linen Tunic',
    type: 'clothes',
    rarity: 'common',
    characterCompatibility: 'both',
    price: 0,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/clothes/tunic_novice.svg',
    description: 'Comfortable everyday adventurer clothing.',
  },
  {
    itemId: 'robe_apprentice',
    name: 'Apprentice Spell Robes',
    type: 'clothes',
    rarity: 'uncommon',
    characterCompatibility: 'both',
    price: 200,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/clothes/robe_apprentice.svg',
    description: 'Deep blue robes embroidered with arcane silver threads.',
  },
  {
    itemId: 'jerkin_rogue',
    name: 'Shadowstalker Leather Jerkin',
    type: 'clothes',
    rarity: 'rare',
    characterCompatibility: 'both',
    price: 450,
    unlockRequirement: { type: 'level', value: 3 },
    asset: '/assets/items/clothes/jerkin_rogue.svg',
    description: 'Supple studded leather crafted for silent agility.',
  },

  // Armor
  {
    itemId: 'iron_plate',
    name: 'Reinforced Iron Cuirass',
    type: 'armor',
    rarity: 'rare',
    characterCompatibility: 'both',
    price: 500,
    unlockRequirement: { type: 'level', value: 4 },
    asset: '/assets/items/armor/iron_plate.svg',
    description: 'Heavy polished iron plates offering sturdy protection.',
  },
  {
    itemId: 'dragon_armor',
    name: 'Dragonscale Mail',
    type: 'armor',
    rarity: 'legendary',
    characterCompatibility: 'both',
    price: 2000,
    unlockRequirement: { type: 'level', value: 10 },
    asset: '/assets/items/armor/dragon_armor.svg',
    description: 'Forged from the tempered scales of the Ancient Fire Drake.',
  },
  {
    itemId: 'golden_plate',
    name: 'Paladin Radiant Aegis',
    type: 'armor',
    rarity: 'mythic',
    characterCompatibility: 'both',
    price: 4500,
    unlockRequirement: { type: 'level', value: 15 },
    asset: '/assets/items/armor/golden_plate.svg',
    description: 'Sacred armor glowing with unstoppable celestial energy.',
  },

  // Weapons
  {
    itemId: 'wooden_sword',
    name: 'Sparring Wooden Blade',
    type: 'weapon',
    rarity: 'common',
    characterCompatibility: 'both',
    price: 0,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/weapons/wooden_sword.svg',
    description: 'A modest wooden practice sword. Every journey starts here.',
  },
  {
    itemId: 'iron_sword',
    name: 'Forged Iron Broadsword',
    type: 'weapon',
    rarity: 'uncommon',
    characterCompatibility: 'both',
    price: 250,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/weapons/iron_sword.svg',
    description: 'Sharp tempered steel balanced for decisive combat.',
  },
  {
    itemId: 'shadow_blade',
    name: 'Obsidian Shadow Dagger',
    type: 'weapon',
    rarity: 'rare',
    characterCompatibility: 'both',
    price: 600,
    unlockRequirement: { type: 'level', value: 5 },
    asset: '/assets/items/weapons/shadow_blade.svg',
    description: 'Smokes with dark energy and slices through tough challenges.',
  },
  {
    itemId: 'mage_staff',
    name: 'Arcane Starlight Staff',
    type: 'weapon',
    rarity: 'epic',
    characterCompatibility: 'both',
    price: 950,
    unlockRequirement: { type: 'level', value: 7 },
    asset: '/assets/items/weapons/mage_staff.svg',
    description: 'Topped with a glowing cosmic crystal pulsating with focus.',
  },
  {
    itemId: 'excalibur',
    name: 'Excalibur, Sword of Legends',
    type: 'weapon',
    rarity: 'mythic',
    characterCompatibility: 'both',
    price: 4000,
    unlockRequirement: { type: 'level', value: 12 },
    asset: '/assets/items/weapons/excalibur.svg',
    description: 'The legendary blade pulled from the bedrock of discipline.',
  },

  // Shoes
  {
    itemId: 'boots_traveler',
    name: 'Traveler Leather Boots',
    type: 'shoes',
    rarity: 'common',
    characterCompatibility: 'both',
    price: 0,
    unlockRequirement: { type: 'none' },
    asset: '/assets/items/shoes/boots_traveler.svg',
    description: 'Comfortable boots built to cross vast continents.',
  },
  {
    itemId: 'greaves_steel',
    name: 'Iron Vanguard Greaves',
    type: 'shoes',
    rarity: 'rare',
    characterCompatibility: 'both',
    price: 350,
    unlockRequirement: { type: 'level', value: 3 },
    asset: '/assets/items/shoes/greaves_steel.svg',
    description: 'Armored boots with reinforced shins and steel toes.',
  },
  {
    itemId: 'boots_winged',
    name: 'Hermes Winged Striders',
    type: 'shoes',
    rarity: 'legendary',
    characterCompatibility: 'both',
    price: 1800,
    unlockRequirement: { type: 'level', value: 8 },
    asset: '/assets/items/shoes/boots_winged.svg',
    description: 'Blessed boots that let your productivity soar effortlessly.',
  },
];

export const SEED_ACHIEVEMENTS = [
  {
    achievementId: 'first_mission',
    name: 'First Blood',
    description: 'Complete your first real-world mission.',
    requirement: { type: 'missions_completed', target: 1 },
    reward: { xp: 50, coins: 30 },
    icon: '⚔️',
  },
  {
    achievementId: 'getting_started',
    name: 'Apprentice of Taskcraft',
    description: 'Conquer 10 missions.',
    requirement: { type: 'missions_completed', target: 10 },
    reward: { xp: 120, coins: 75 },
    icon: '📜',
  },
  {
    achievementId: 'warrior',
    name: 'Battle-Hardened Hero',
    description: 'Conquer 50 missions.',
    requirement: { type: 'missions_completed', target: 50 },
    reward: { xp: 400, coins: 250, itemId: 'knight_helm' },
    icon: '🛡️',
  },
  {
    achievementId: 'veteran',
    name: 'Living Legend',
    description: 'Conquer 100 missions.',
    requirement: { type: 'missions_completed', target: 100 },
    reward: { xp: 1000, coins: 600, itemId: 'shadow_blade' },
    icon: '👑',
  },
  {
    achievementId: 'level_5',
    name: 'Rising Star',
    description: 'Reach Level 5.',
    requirement: { type: 'level', target: 5 },
    reward: { xp: 150, coins: 100 },
    icon: '⭐',
  },
  {
    achievementId: 'level_10',
    name: 'Champion of the Realm',
    description: 'Reach Level 10.',
    requirement: { type: 'level', target: 10 },
    reward: { xp: 500, coins: 350 },
    icon: '🌟',
  },
  {
    achievementId: 'legend',
    name: 'God of Productivity',
    description: 'Reach Level 50.',
    requirement: { type: 'level', target: 50 },
    reward: { xp: 2500, coins: 2000, itemId: 'excalibur' },
    icon: '⚡',
  },
  {
    achievementId: 'streak_3',
    name: 'Building Momentum',
    description: 'Maintain a 3-day active streak.',
    requirement: { type: 'streak', target: 3 },
    reward: { xp: 60, coins: 50 },
    icon: '🔥',
  },
  {
    achievementId: 'streak_7',
    name: 'Unstoppable Momentum',
    description: 'Maintain a 7-day active streak.',
    requirement: { type: 'streak', target: 7 },
    reward: { xp: 250, coins: 150, itemId: 'golden_crown' },
    icon: '💥',
  },
  {
    achievementId: 'dedicated',
    name: 'The Grand Master',
    description: 'Maintain a 30-day active streak.',
    requirement: { type: 'streak', target: 30 },
    reward: { xp: 1200, coins: 1000 },
    icon: '🏆',
  },
  {
    achievementId: 'fashionista',
    name: 'Armory Connoisseur',
    description: 'Collect 8 or more items in your inventory.',
    requirement: { type: 'items_owned', target: 8 },
    reward: { xp: 180, coins: 120 },
    icon: '🎒',
  },
];
